# Generated by Django 5.0.4 on 2024-05-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order'], 'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказов'},
        ),
    ]
